### PR TITLE
Preserve metadata when wrapping collections

### LINKED ISSUE #291: Collection metadata is lost during instrumentation
Collection metadata is lost during instrumentation, e.g.:

```
=> (in-ns cloverage.instrument)
=> (meta (macroexpand-1 (instrument-form #'no-instr nil ^:preserved? [:foo :bar])))
nil
```

This only becomes of practical concern when source code applies metadata to collections via the reader i.e. `^`

### PR DESCRIPTION
**Pull request by jameslintaylor**
- fixes #291

### CODE REVIEW

**Comment by lvh** [comment]
Thanks!

**Comment by jameslintaylor** [comment]
Hey @lvh, thanks for your maintainership of cloverage and for reviewing this PR. 

Do you have any idea on when the next release will be cut?

**Comment by lvh** [comment]
I'm kinda slammed today but I'm hoping to get to it some time in the immediate future.

In the mean while: SNAPSHOT releases are cut as part of CI, so if you need this feature now, you might just want to run -SNAPSHOT.

**Comment by lvh** [comment]
1.1.3 is now on Clojars.

**Pull request merged**
