### PR TITLE
Only call `gather-stats` once

### PR DESCRIPTION
**Pull request by rm-hull**
`gather-stats` will enumerate over all files processing them: for large
codebases it makes no sense to do this more than once

### CODE REVIEW

**Comment by rm-hull** [comment]
p.s. there will be a merge conflict between this and #165 - will fix in whichever lands first

**Comment by lvh** [comment]
Yep; please update this PR.

**Comment by rm-hull** [comment]
merge conflict fixed

**Comment by lvh** [comment]
Thanks!

**Pull request merged**
