### PR TITLE
Fix junit result generation

### PR DESCRIPTION
**Pull request by iafilatov**
Probably forgot to rename in 66229129b2b88c2c431de6c92e4ccc924e286c68

### CODE REVIEW

**Comment by lvh** [comment]
Whoops; thanks!

**Comment by iafilatov** [comment]
Looks like lein-cloverage version isn't synchronized with cloverage. E.g. even if I set lein-cloverage to 1.0.12-SNAPSHOT in :plugins, lein still pulls 1.0.11 of cloverage. Is it expected?

**Comment by lvh** [comment]
Are you sure you're not setting CLOVERAGE_VERSION somewhere?

**Comment by iafilatov** [comment]
No, and it appears to default to "RELEASE" https://github.com/cloverage/cloverage/blob/3422233549a0f49adfc64e9af3fe02dd76897307/lein-cloverage/src/leiningen/cloverage.clj#L6-L7

**Comment by lvh** [comment]
Sorry, I misunderstood: you should set CLOVERAGE_VERSION to a SNAPSHOT :) I think that changed at one point, but I can't remember.

**Comment by lvh** [comment]
@timgilbert I have released 1.0.12.

**Comment by timgilbert** [comment]
Awesome, thanks @lvh! Works like a charm for me so far.

**Comment by lvh** [comment]
There's also 1.0.13 out now which should even work on Java 10 :)

**Pull request merged**
