### PR TITLE
Add Open JDK 11 and EA to test matrix

### PR DESCRIPTION
**Pull request by danielcompton**

### CODE REVIEW

**Comment by lvh** [comment]
Hoo boy. OK: looks like Travis killed OpenJDK 6 and 7 and we should axe support for those. I want to add 11 and EA, but don't understand the failure. I guess cov/find-nses is just busted on post-Jigsaw JDKs?

**Comment by danielcompton** [comment]
Yeah that does seem like a reasonable stepping stone. I can take a look too.

**Comment by danielcompton** [comment]
I've done a bit more digging, and the issue appears to be in the changes to the JDK. In the REPL from the `dynapath.util` ns:

```clj
;; Java 8

(->> (iterate #(.getParent ^ClassLoader %) (clojure.lang.RT/baseLoader))
     (take-while identity)
     reverse)
=>
(#object[sun.misc.Launcher$ExtClassLoader 0x5e4cf6a4 "sun.misc.Launcher$ExtClassLoader@5e4cf6a4"]
 #object[sun.misc.Launcher$AppClassLoader 0x18b4aac2 "sun.misc.Launcher$AppClassLoader@18b4aac2"]
 #object[clojure.lang.DynamicClassLoader 0x375dab93 "clojure.lang.DynamicClassLoader@375dab93"]
 #object[clojure.lang.DynamicClassLoader 0x64a2453b "clojure.lang.DynamicClassLoader@64a2453b"]
 #object[clojure.lang.DynamicClassLoader 0x56b1e527 "clojure.lang.DynamicClassLoader@56b1e527"]
 #object[clojure.lang.DynamicClassLoader 0x5a05b614 "clojure.lang.DynamicClassLoader@5a05b614"])

(->> (iterate #(.getParent ^ClassLoader %) (clojure.lang.RT/baseLoader))
     (take-while identity)
     reverse
     (map dc/can-read?))
=> (true true true true true true)


;; Java 11
(->> (iterate #(.getParent ^ClassLoader %) (clojure.lang.RT/baseLoader))
     (take-while identity)
     reverse)
=>
(#object[jdk.internal.loader.ClassLoaders$PlatformClassLoader
         0x7a03e6bc
         "jdk.internal.loader.ClassLoaders$PlatformClassLoader@7a03e6bc"]
 #object[jdk.internal.loader.ClassLoaders$AppClassLoader
         0x512ddf17
         "jdk.internal.loader.ClassLoaders$AppClassLoader@512ddf17"]
 #object[clojure.lang.DynamicClassLoader 0x315f43d5 "clojure.lang.DynamicClassLoader@315f43d5"]
 #object[clojure.lang.DynamicClassLoader 0x75390459 "clojure.lang.DynamicClassLoader@75390459"]
 #object[clojure.lang.DynamicClassLoader 0x6ad3fbe4 "clojure.lang.DynamicClassLoader@6ad3fbe4"]
 #object[clojure.lang.DynamicClassLoader 0x4cff3407 "clojure.lang.DynamicClassLoader@4cff3407"])

(->> (iterate #(.getParent ^ClassLoader %) (clojure.lang.RT/baseLoader))
     (take-while identity)
     reverse
     (map readable-classpath?))
=> (false false true true true true)
```

I'll need to do some more digging, but this might need a patch to Dynapath to extend it to read the jdk internal class loaders (!).

**Comment by lvh** [comment]
Awesome. I'm surprised we're the first people to hit this! Perhaps we're just the first to debug it :)

**Comment by lvh** [comment]
I think this is no longer necessary because of #259.

**Pull request closed without merging**
