### PR TITLE
Kaocha

### PR DESCRIPTION
**Pull request by AndreaCrotti**
Use kaocha to run tests in cloverage/cloverage

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
The only failure that I'm still getting (running `./bin/kaocha`) is

```FAIL in cloverage.coverage-test/test-wrap-str (cloverage/coverage_test.clj:167)
Test ran without assertions. Did you forget an (is ...)?
70 tests, 234 assertions, 1 failures.
Error encountered performing task 'run' with profile(s): 'dev'
Suppressed exit```

**Comment by AndreaCrotti** [comment]
Ah right I  just noticed now that there are both travis.ci and circleci configurations in the project,  but neither are integrated in Pull requests at the moment.
Would be nice to enable that too (only a project admin can do that) to see if PRs are breaking tests.

**Comment by AndreaCrotti** [comment]
I updated the circleci config as well, but I don't see this project in circleci so I guess it's not fully set up there.
Anyway I fixed the failing test just adding a simple assertion, so `lein kaocha` or `./bin/kaocha` passes now.

**Comment by lvh** [comment]
I'd love to get the CI situation working properly, but due to various issues with both Travis and Circle I think i'd be happiest if that moved to GitHub Actions, and that's an unreasonable thing to ask of you when you've already done so much :) So for now I'm going to give it a shot and revert if it breaks.

**Pull request merged**
