### PR TITLE
Remove things from TODO.md tracked in issues

### PR DESCRIPTION
**Pull request by lvh**

### CODE REVIEW

**Comment by lvh** [comment]
The failure is because of broken CircleCI (fixing in another PR) and cljfmt (fixed in #151).

**Comment by lvh** [comment]
CircleCI did not end up needing another PR; the broken test command was added (and removed) via the UI.

**Comment by FossiFoo** [comment]
Maybe we should just track all of them in issues? To me it does not make much sense to have 2 "TODO" lists.

**Comment by lvh** [comment]
Yep, that's the goal. I just wanted to start by getting rid of the ones that are _already_ tracked in the issue tracker so I don't have to weed out the issue tracker first to see if something is somehow tracked in there.

**Pull request merged**
