### PR TITLE
Support excluding call sites by fn/macro name

### LINKED ISSUE #241: Support excluding call sites by fn/macro name
In principle, I prefer having 100% test coverage _with explicit exclusions_, rather than using a lower percentage that permits arbitrary code to remain uncovered. Toward this goal, the `:ns-exclude-regex` feature has been critical.

I am currently using [outpace.config/defconfig](https://github.com/outpace/config#config-usage), and as with [`defmulti`](https://github.com/cloverage/cloverage/blob/aebb716890103348a05d38d6a89f66374f69d4d6/cloverage/src/cloverage/instrument.clj#L392-L393), achieving full coverage of the macro call site effectively requires testing the macro itself.

So, in keeping with the purpose of `:ns-exclude-regex`, I propose adding a feature to exclude specific macro's call sites from instrumentation.

### PR DESCRIPTION
**Pull request by ataggart**
Fixes #241

### CODE REVIEW

**Comment by ataggart** [comment]
Using `lein with-profile +sample test` passes locally.

**Comment by lvh** [comment]
Per the ticket: you mention "specific macro call sites" but this appears to exclude the macro for all call sites. Am I missing something or is that how it works? (That's fine! I just want to make sure I understand what I'm pulling in :))

**Comment by ataggart** [comment]
The macro call site is the motivation (and perhaps the only valid use case), but it is implemented in terms of any call site. I didn't see a reason to overly constrain the behaviour, nor incur the cost of verifying whether the symbol names a macro.

**Comment by ataggart** [comment]
And now I see I misread your query.  To be clear, the intention is to affect all call sites of a specific macro. :)

**Comment by lvh** [comment]
thanks for your contribution! this looks great :)

**Comment by ataggart** [comment]
Thanks for the rapid response! Do you know when you will cut the next release?

**Comment by lvh** [comment]
Someone needs to fix up the changelog from last night's release (possibly me) first. I just changed the way releases are cut (this is an ancient codebase that was still loading the `lein-release` plugin). With a little luck, -SNAPSHOT releases are still cut automatically by CI.

**Comment by ataggart** [comment]
I see cljfmt doesn't like my formatting. I can push up a change, but I'm not clear on what it wants.

**Comment by lvh** [comment]
Oh, crud.  https://travis-ci.org/cloverage/cloverage/jobs/502822342 suggests it might just be eclint?

Unfortunately I've been ignoring CI failings until I get around to getting JDK9+ (specifically post-Jigsaw) JVMs working.

**Comment by ataggart** [comment]
CircleCI seems to be working. https://circleci.com/gh/cloverage/cloverage/89

Digging into the formatting now.

**Comment by ataggart** [comment]
> Someone needs to fix up the changelog from last night's release (possibly me) first. I just changed the way releases are cut (this is an ancient codebase that was still loading the `lein-release` plugin). With a little luck, -SNAPSHOT releases are still cut automatically by CI.

@lvh I'm happy to update the changelog. To that end, how are you versioning things now? I notice historically `lein-cloverage` and `cloverage` had different versions.

**Comment by lvh** [comment]
That's a bug; I've just updated the versions, changelogs, and am about to cut a release.

**Comment by lvh** [comment]
FWIW the underlying bug why 1 version wasn't getting updated is because lein release wants to git tag a release (which makes sense) but the previous maintainer decided to put cloverage + its lein plugin in the same repo. To fix that, you'd want the tags to not just be versions but also include _what specifically_ it's a version of. Or not tag lein plugin versions, or have 2 repos I guess :)

**Comment by ataggart** [comment]
Thanks for the release!

Two projects in one repo seems to be the pattern most plugins take, though I'm not clear on why.

One notable exception is `eastwood`, which keeps [both namespaces in the same `src`](https://github.com/jonase/eastwood/tree/master/src). I tried to do that with `cloverage`, but it caused some failing tests. If I have time later, I may try to figure out why.

**Pull request merged**
