### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nwjsmith**
Notably update the AOT-ed `tools.reader` to the latest version, and swap Bultitude for tools.namespace so that cloverage can run properly on Java 9+.

### CODE REVIEW

**Comment by nwjsmith** [comment]
@lvh I'm not sure if you're looking for someone to take on maintenance of Cloverage, but I'd be happy to if that's the case. It's critical to my workflow, and I would be happy to start working through the backlog of issues.

**Comment by lvh** [comment]
Heya! I don't do development work, but I review and cut releases. Pretty happy to have new blood working on it :)

**Comment by lvh** [comment]
Uhhh, my email says there was a comment where @nwjsmith suggested maintainerhood, I promise I'm not talking to myself :)

**Comment by nwjsmith** [comment]
@lvh haha yeah sorry I deleted my comment, but after I looked at your recent work on Cloverage I worried it might have been rude for me to suggest I maintain it. I'll try to start working through some of the issues, happy to lend a hand :)

**Comment by lvh** [comment]
Whoops, I didn't realize the build started passing, hooray! Thank you so much for working on this.

**Pull request merged**
