### PR TITLE
Ensure custom data readers are installed before running `cloverage`

### PR DESCRIPTION
**Pull request by skuro**
If any custom `data_readers.clj` file is provided either in sources or
through dependencies, currently `cloverage` ignores them and fails to read
the sources. I discovered the issue while working with `honeysql` and its
`#sql/call` literals.

This change ensures that all data readers from either source code or through
dependencies are properly communicated to `tools.reader` before unleashing
`cloverage`.

Most likely solves #197 as well

### CODE REVIEW

**Comment by lvh** [comment]
Super clean, thanks!

**Comment by Leulz** [comment]
Any estimate on when this change will be on a release? I want to use cloverage but my company uses a lot of custom data-readers, so I can't. :(

**Comment by skuro** [comment]
@Leulz I'm kinda in the same position at the moment, so I've cut a temporary frelease (fork release -- gonna rush to boy the domain *now*) at [`skuro/lein-cloverage`](https://clojars.org/skuro/lein-cloverage)

**Comment by lvh** [comment]
@skuro @Leulz Travis CI builds include new snapshots, so if you're happy with 1.2.1-SNAPSHOT you never need to use a third-party build.

**Comment by lvh** [comment]
(I have also just cut a new proper release and updated the CHANGELOG.)

**Comment by skuro** [comment]
Awesome thanks! I usually avoid `SNAPSHOT` dependencies for anything serious, hence the temporary stopgap release. I already switched back to the main `cloverage` release.

**Pull request merged**
