### PR TITLE
[Fixes #143] Add kibit and eastwood to CI

### LINKED ISSUE #143: Add kibit/eastwood to CI

### PR DESCRIPTION
**Pull request by gonewest818**
This PR includes the changes necessary to run `kibit` and `eastwood` in Travis CI *and* addresses the issues raised when running those tools.

For everyone's sanity I've tried to "group" the changes: a single commit contains fixes needed to satisfy eastwood, another commit for the kibit warnings, another commit for cljfmt, and so on. (Along the way I've gotten a lot more comfortable with magit's interactive rebase with reordering, rewording, and squashing commits).

Obviously, this isn't ready to merge but you can take a look and start thinking about what it will take for you to be comfortable merging this in.

There's a problem I don't yet understand, but I've documented in a comment in `src/cloverage/sample/cyclic_dependency.clj`. Basically Eastwood throws an exception on that file because of the cyclic dependency, and it's not even possible to *exclude* the file from Eastwood analysis in a way that avoids the exception. However, if I modify the file in a way that satisfes Eastwood then I break the unit test. Which means Travis CI is doomed to fail one way or the other. I'm open to suggestions or insights from you how to approach this issue.

### CODE REVIEW

**Comment by lvh** [comment]
that cyclic dependency issue sounds like it warrants a bug in eastwood so I filed one: https://github.com/jonase/eastwood/issues/252

**Comment by gonewest818** [comment]
I believe we can resolve this issue with eastwood by moving `cyclic_dependency.clj` out of `src/cloverage/sample` and into `sample/cloverage/sample`, with a new profile ":sample {:source-paths ["sample"]}`. 

The net result is you can run `lein with-profile +sample ...` when you want those files included in the build or analysis, and drop the `+sample` when you don't want them.

Questions:
  - Do the `cloverage.sample.*` namespaces need to be compiled and distributed in the jar?
  - Would you rather have `cyclic_dependency.clj` and `exercise_instrumentation.clj` located in the same directory (and therefore both excluded from eastwood)?  Alternative is to have them in two directories `src/cloverage/sample/exercise_instrumentation.clj` and `sample/cloverage/sample/cuclic_dependency.clj`, so that the former is still analyzed by eastwood but the latter is not.

**Comment by gonewest818** [comment]
Anything more to do for this?

**Comment by lvh** [comment]
@gonewest818 sorry about that; just needed some reviewer time :)

**Comment by lvh** [comment]
I reverted this in #205 because it broke master with this build: https://circleci.com/gh/cloverage/cloverage/61?utm_campaign=build-failed&utm_medium=email&utm_source=notification

I don't have time to look at it right now but I might later today. Probably a CircleCI-only failure, since this updated Travis CI but not CircleCI. This slipped through the cracks because apparently CircleCI only operates on master, not individual branches.

**Comment by gonewest818** [comment]
I missed that — are you using both? Migrating from one to the other?

**Comment by lvh** [comment]
Both. No particular reason other than that the CircleCI folks are avoid cloverage users. I'll admit that I'm not particularly convinced of the utility of having both, even though I like CircleCI and generally recommend them as a service :) (See CircleCI PRs for details.)

**Comment by gonewest818** [comment]
Ok, well apologies for that.  I've never worked with CircleCI configuration, but if you want me to finish what I started just let me know.  It doesn't look that complicated. Conceptually the changes are as follows:

For `working_directory: ./cloverage`
1. `lein test` needs to be `lein with-profile +sample test` where the `+sample` profile is used to split out the circular dependency.
2. you need a task for `lein cljfmt check`
3. you need a task to run eastwood two times:
```
lein eastwood "{:exclude-namespaces [cloverage.sample.exercise-instrumentation]}"
```
and 
```
lein eastwood "{:namespaces [cloverage.sample.exercise-instrumentation] \
                            :exclude-linters [:unused-ret-vals \
                                              :suspicious-test \
                                              :constant-test \
                                              :wrong-pre-post]}"
```
4.  you need a task for `lein kibit`

For `working_directory: ./lein-cloverage` all these will be generic
5. `lein test` should not need to be changed
6. `lein cljfmt check`
7. `lein eastwood`
8. `lein kibit`

**Pull request merged**
