### PR TITLE
111 hiccup

### PR DESCRIPTION
**Pull request by LukasRychtecky**
Hi,

I've replace generating HTML by Hiccup library. Please feel free to comment my PR.

Screenshots for comparison:
screen shot 2018-01-19 at 16 28 43

screen shot 2018-01-19 at 16 29 02

Thanks

### CODE REVIEW

**Comment by lvh** [comment]
Thanks for your contirbution! As #111 notes, #109 has to be resolved first: Hiccup is a common library, and cloverage therefore shouldn't conflict with dependencies in the projects it instruments.

**Comment by LukasRychtecky** [comment]
@lvh Oh, sorry I saw a reference for #103 (as closed), thus I overlooked #109. Hmm I've checked the Eastwood's approach. It seems that there is no otherway how to handle different dependencies.

**Comment by lvh** [comment]
Yep. So the good news is that this still does really useful work we eventually want to incorporate (using a real HTML library for the HTML reports), but the bad news is we can't incorporate it until we have a way of vendoring those dependencies. Since all of the relevant issues have this PR linked, we can revisit it when that other work as been done. Until then, I'm afraid that the only thing we can do is close this PR :( I'm really sorry, having done good work and then not having it implemented sucks :(

**Comment by LukasRychtecky** [comment]
I understand the issue, no problem. I'll keep the branch and I can rebase it in future. I'll try to help anyway.

**Pull request closed without merging**
