### PR TITLE
Update the changelog for the 1.0.7 release

### PR DESCRIPTION
**Pull request by lvh**

### CODE REVIEW

**Comment by rfkm** [comment]
The changelog seems not to cover all changes in 1.0.7. (E.g., cljc, midje support)

**Comment by lvh** [comment]
@rfkm How do you use the midje support? The README currently instructs people to do deftest wrapping, is that still necessary?

**Comment by lvh** [comment]
Looks like the answer is `-r :midje`?

**Comment by rfkm** [comment]
> Looks like the answer is -r :midje?

Yep! `-r midje` should also be ok. `deftest` is no longer necessary.

**Pull request merged**
